### ISSUE TITLE
MakeMKV can't see any usable optical drives

### ISSUE THREAD

**Issue by kz6fittycent** [diddlesnaps/makemkv#1]
I was reading thru your posts on forum.snapcraft.io regarding confinement and some Apparmor issues. 

I'm curious as to whether you're experiencing anything like what I'm seeing:

```
MakeMKV v1.12.3 linux(x64-release) started
The program can't find any usable optical drives.
```

This was an issue we faced as Solus users and it's remedied (for a native application) via:

```
sudo modprobe sg
```

This doesn't appear to be the case with the snap. Running the above command does nothing (I figured it wouldn't). I bring it up as I'm hoping to help out in any way possible.

**Comment by diddledan** [comment]
I don't have the `sg` module loaded at all. AFAICT the only related modules I have loaded are `ahci` and `libahci`. My bluray drive is exposed at `/dev/sr0`.

**Comment by kz6fittycent** [comment]
Yeah typically when running it on *buntu there's no need to run `modprobe`; I haven't verified that `sg` is already loaded in the Ubuntu kernel (as I'm not running it at all).

**Comment by kz6fittycent** [comment]
What are the odds of getting this snap classic confinement? 

Given that other distros may not be loading `sg` automatically like Ubuntu seems to do, there might be a good case for this, unless you feel differently.

**Comment by kz6fittycent** [comment]
I know it's been a while, but I figured out some things for Solus:

The path for DVD's, et cetera is - /run/media/<user>/VIDEO_NAME

Hopefully this will help someone else running into the same issue I was. The good news is that I am in the middle of ripping an old John Wayne move (The Comancheros). :100:

**Comment by kz6fittycent** [comment]
Getting closer! So, I have a USB Blu-ray player and the snap isn't detecting it. Any ideas? 

It's not there at all, though the OS (Solus) is seeing it at /run/media/$USER/.

**Comment by diddledan** [comment]
I've released makemkv to stable, with strict confinement. Can you test again with the latest build (number 97 for amd64 systems). You _do_ need the `sg` module either compiled-into your kernel or loaded as a module.

**Comment by kz6fittycent** [comment]
DUDE!!!! YOU ARE MY FRIGGIN' HERO!!!

It's working on a USB BD Drive and I'm ripping a BD at this very moment w/o any errors. 

I did have to run `sudo modprobe sg` on Solus and after that, works like a charm. 

Thanks so much for your hard work on this. You may have saved Solus :P

**Comment by kz6fittycent** [comment]
I'd previously connected all the interfaces before you asked, but for the record, this is how my snap is configured:

```
snap connections makemkv 
Interface         Plug                      Slot               Notes
desktop           makemkv:desktop           :desktop           -
desktop-legacy    makemkv:desktop-legacy    :desktop-legacy    -
gsettings         makemkv:gsettings         :gsettings         -
hardware-observe  makemkv:hardware-observe  :hardware-observe  manual
home              makemkv:home              :home              -
network           makemkv:network           :network           -
opengl            makemkv:opengl            :opengl            -
optical-drive     makemkv:optical-drive     :optical-drive     -
process-control   makemkv:process-control   :process-control   manual
removable-media   makemkv:removable-media   :removable-media   manual
unity7            makemkv:unity7            :unity7            -
wayland           makemkv:wayland           :wayland           -
x11               makemkv:x11               :x11               -
```

**Comment by kz6fittycent** [comment]
After over a week of flawless use, I think it's safe to say this ticket should be closed. I thank you once again for a job well done!
