### ISSUE TITLE
makemkv should use a different standard storage folder

### ISSUE THREAD

**Issue by GeorgScheumann** [diddlesnaps/makemkv#10]
Hello,

I recently saw a user in a support forum who had issues because he saved all his movies in the standard directory. As the snap updated, according to him hundreds of gigabytes were copied to the new revision. So this essentially reduced his available disk space a lot and he found it out, but I believe a lot of users won't and this can cause serious trouble for them. So maybe something like /home/$USER/movies should be used as a standard directory instead of $HOME/snap/makemkv/revision.

Best regards ;)

**Comment by diddledan** [comment]
Thanks for the report. I think the commit I just added will fix this. It is building now and will be available in the `edge` channel of the Snap Store soon.
