### ISSUE TITLE
Unable to execute external program 'ccextractor' as its path is not set in preferences

### ISSUE THREAD

**Issue by Hooloovoo** [diddlesnaps/makemkv#11]
Many thanks for this snap!

When I try to rip a DVD containing Closed Captions, I get the following error:
`Saving 1 titles into directory /home/shared
Unable to execute external program 'ccextractor' as its path is not set in preferences
Failed to execute external program 'ccextractor' from location '/snap/makemkv/232/usr/bin/mmccextr'
Failed to save title 0 to file /home/shared/title_t00.mkv
0 titles saved, 1 failed`

I see that you actually do include CCExtractor in the snap and you can resolve this by going into the preferences, clicking Expert mode > Advanced > ccextractor executable location: "/usr/bin/ccextractor"

It would be great if you could pre-populate that setting for people or come up with another way that MakeMKV could auto-detect the install location.

This link:
https://www.makemkv.com/forum/viewtopic.php?t=18362
has some info on where the setting is stored etc. If you can make it work then you could also advertise your snap there as an easy way to solve the problem for anyone who comes across that thread.

**Comment by diddledan** [comment]
Thanks for the report. I think the commit I just added will fix this. It is building now and will be available in the `edge` channel of the Snap Store soon.
