### ISSUE TITLE
Network plug

### ISSUE THREAD

**Issue by kz6fittycent** [diddlesnaps/makemkv#2]
I think this may need the network plug as when I attempt to rip my BD's, it fails to complete and cannot download any updates to decrypt BD's.

**Comment by kz6fittycent** [comment]
I've forked your repo and I'm testing it out. So far, it seems that it's working as intended. It was able to successfully complete registration (I can't remember if that was a problem before). I am ripping a movie now. Will let you know how it turns out.

**Comment by diddledan** [comment]
Even if it does need the network plug when it finally works in strict mode, currently it is in devmode so the access will still be granted anyway.

**Comment by kz6fittycent** [comment]
You're right and I did forget about that. Anyway, it's having a problem ripping BD's. It can rip DVD's all day long but it fails to decrypt BD's. This may be associated with the AAC's are missing and can't be updated (or just aren't being updated). I'll keep testing to see what I can find out.

**Comment by diddledan** [comment]
The snap includes the `network` plug and is released to stable now.
