### ISSUE TITLE
Unable to access removable media

### ISSUE THREAD

**Issue by suprkain** [diddlesnaps/makemkv#4]
I installed the snap from Ubuntu software and the program cannot access my 2nd internal hard drive.  I gave it permission to Read/write files on removable storage devices but I do not see it anywhere

**Comment by diddledan** [comment]
Your removable storage must be mounted to either `/media/$USERNAME/*` or `/mnt/*` any other location is not accounted for by the "Read/write files on removable storage" permission.

**Comment by suprkain** [comment]
I navigated to /media/$USERNAME from within the terminal and am able to see and access my 2nd hard drive.  I also went to my 2nd hard drive from within Nautilus and right clicked and choose "Open in Terminal".  I then did a pwd and got /media/$USERNAME/Delta (which is my second hard drive)

**Comment by suprkain** [comment]
Also when I try to navigate via the file manager from within the makemkv snap I do not see /media at all.

**Comment by suprkain** [comment]
I click Computer--> / but then I do not see media even though I gave it permission to through the ubuntu store.

**Comment by kz6fittycent** [comment]
Which distro and did you try `sudo modeprobe sg`?

**Comment by kz6fittycent** [comment]
I wondering if you need to run `sudo modprobe usb-storage`? 

I know that's maybe counterintuitive but it's easy enough to give it a try. 

The other idea is to try running the snap in `--devmode` and see if anything changes.

**Comment by suprkain** [comment]
I tried snap run makemkv --devmode but that did not change anything. 
I tried lsmod | grep usb and did not see usbcore or usbcommon.  What I get is below:
btusb                  57344  0
btrtl                  20480  1 btusb
btbcm                  16384  1 btusb
btintel                24576  1 btusb
bluetooth             581632  31 btrtl,btintel,btbcm,bnep,btusb,rfcomm
usb_storage            77824  1 uas

I am running kernal version 5.3.0-23-generic.

As far as modprobe usb-storage would this affect and internal hard drive?  I tried it however but with no luck.

**Comment by kz6fittycent** [comment]
Try running `sudo modprobe usb_storage`

I think I misspoke before.

**Comment by suprkain** [comment]
I'm not sure if it helps but with other Snaps when I go to look for files it opens Nautilus but when I go through Makemkv snap the file manager looks different than the standard Nautilus.

**Comment by kz6fittycent** [comment]
LOL, it might help if I READ your issue. I didn't realize this was an internal hard-drive!!

In the application (MakeMKV), instead of looking for the drive, try typing it in the file name field below: 

File> Open files > (Next to "File name:") Type the path to the internal drive (e.g. `/mnt/extra_drive` or `/extra_drive`)


![Peek 2019-11-17 20-12](https://user-images.githubusercontent.com/14829816/69019725-77917100-0977-11ea-800b-5c099185952d.gif)

Also, if you're not sure what the path for that drive is, you can run `findmnt` from your terminal to see how it's really mounted. 

It might not be in mounts, it can just be part of the `/` directory as is the case for one of my PC's (i.e. `/data01/`).

**Comment by kz6fittycent** [comment]
Here's another example where I'm looking for it in `/run/media`. I realize this isn't your case but it's just another example of what I'm talking about:

![Peek 2019-11-17 20-29](https://user-images.githubusercontent.com/14829816/69020120-1b2f5100-0979-11ea-861e-20d308c0b285.gif)

**Comment by suprkain** [comment]
I am able to see it if I manually type it in.  I thought I had tried that early but I guess not.  Not sure why an internal hard drive is showing up in media and not mount but I'll figure that out.  Thanks for your help.
