### ISSUE TITLE
snap uses per-version storage for persistent files

### ISSUE THREAD

**Issue by philpennock** [diddlesnaps/makemkv#5]
I've purchased a license key for MakeMKV, so after entering it double-checked to make sure it would be persisted.  Looking in `~/snap/makemkv/` I would hope to see `.MakeMKV/settings.conf` under `common/`; instead it's in `167/` (target of symlink `current`).

When the snap updates, I will "lose" my licensing state.

**Comment by diddledan** [comment]
No, this is fine. The files in the versioned directories are copied wholesale into a new version directory when the snap refreshes. The only ways you'll lose the licensing state are:

- you delete the directories under `~/snap/makemkv`
- you roll back to a revision that was unlicensed
- you uninstall the snap

**Comment by philpennock** [comment]
Sorry.  That's what I get for not looking at snap internals for a few years and then relying upon faulty memory.
