### ISSUE TITLE
Makemkv snap fatal error

### ISSUE THREAD

**Issue by bkurt78** [diddlesnaps/makemkv#6]
I'm trying to rip a blu-ray and it gets to a point where it hits a playlist or .mpls file.  At that point the program mentions that it is using java to handle the playlist.  It is at this point that the program hangs and reports a fatal error.  

Based on some research I did there was some indications that this was a result of using an older version of java.  In my case it was still using java 8.  I tried installing a newer version of java and pointing the application at the new version of java, but I couldn't browse to the new java location.  I'm assuming this is a confinement issue perhaps, but I'm relatively new to snaps so I could be completely wrong.

This is on ubuntu 19.10 with version 1.72 of the snap package.  I tried generating the log file, but it didn't really log anything other than the part about starting to use java when things fail.  Let me know if I can provide any more information.  Thank you!

**Comment by kz6fittycent** [comment]
Yeah the version of java being referenced is confined in the snap. I've not experienced this issue. Are you running the snap in devmode? 

Also the Linux version of Makemkv is behind the Windows version, which can mean we don't get some of the newest goodies.

**Comment by diddledan** [comment]
> This is on ubuntu 19.10 with version 1.72 of the snap package.

It's certainly curious that you have version 1.72 of makemkv in a snap, because makemkv is currently sitting at version 1.15.0, which is also what is currently in the stable channel in the store.

**Comment by bkurt78** [comment]
Sorry for the confusion.  It is version 172 of the snap package I believe.  It is makemkv version 1.15.  Here is the tail end of the snap info makemkv output:

snap-id:      oQi5445Bw83J591pCgmPm8lCBNkvrL0w
tracking:     latest/stable
refresh-date: yesterday at 02:18 EDT
channels:
  stable:    1.15.0 2020-03-06 (167) 180MB -
  candidate: ↑
  beta:      ↑
  edge:      1.15.0 2020-03-11 (172) 180MB -
installed:   1.15.0            (167) 180MB -

**Comment by bkurt78** [comment]
> 
> 
> Yeah the version of java being referenced is confined in the snap. I've not experienced this issue. Are you running the snap in devmode?
> 
> Also the Linux version of Makemkv is behind the Windows version, which can mean we don't get some of the newest goodies.

I am not running it in devmode.  Would that be something to try?

**Comment by diddledan** [comment]
>  It is version 172 of the snap package I believe. It is makemkv version 1.15.

Aah, sorry I got confused by the point `.` :-)

It looks like you're actually running the stable build, revision 167 with version 1.15.0. I'm unsure why the java would be failing for you, as I have definitely had this work for my own rips but "works on my PC" isn't a satisfactory answer :-)

**Comment by bkurt78** [comment]
I should clarify a bit further in that it has worked for many discs just fine, but this particular one is not working.  I started reading in the forums and found that java is apparently used when the disc uses some sort of playlist obfuscation.  Here is a link to one of the forum posts that seemed related.
https://makemkv.com/forum/viewtopic.php?f=1&t=16791

**Comment by bkurt78** [comment]
Just pulled in the updated version from the edge channel and it worked!  Thank you so much!

**Comment by kz6fittycent** [comment]
I have installed the edge version, too. I don't have anything to rip at the moment but will report back once I do. 

P.S. I thought you had changed the icon to that schweet one? :P

**Comment by kz6fittycent** [comment]
Uh oh! I just decided to try running the `--edge` version on Solus and this happened!

```
error: cannot perform the following tasks:
- Run post-refresh hook of "makemkv" snap if present (run hook "post-refresh": 
-----
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
+ mkdir -p /var/snap/makemkv/173/etc/ld.so.conf.d
+ cp -r '/etc/ld.so.conf.d/*' /var/snap/makemkv/173/etc/ld.so.conf.d
cp: cannot stat '/etc/ld.so.conf.d/*': No such file or directory
-----)
```

Granted, Solus is using snapd version `2.39.3` so that may be an issue.

**Comment by kz6fittycent** [comment]
Working now! Thanks Dan.

**Comment by diddledan** [comment]
Is everyone happy for me to close this issue or are you still having trouble?

**Comment by bkurt78** [comment]
All good on my end of things.

**Comment by kz6fittycent** [comment]
Yeah close it! Thanks Dan.

**Comment by diddledan** [comment]
awesome, thanks :-)
