### ISSUE TITLE
Can't save to directory on a different drive

### ISSUE THREAD

**Issue by blessedbiped** [diddlesnaps/makemkv#9]
Not sure whether this is an issue or a fault in my understanding of snaps, but I cannot save to a different drive (I have a big spinning data drive expressly for storing large data while I'm working on it). This was my default behavior using the ppa, now I can't seem to browse to /media/data/ in the save browser. I tried making a symlink to it in my regular home directory but permissions are denied. Is this not supported in snaps, or is there something I can change to get my regular workflow back?

**Comment by blessedbiped** [comment]
Bind mounts seem to work to an extent, not certain if that's a particularly user friendly solution.

**Comment by diddledan** [comment]
There's a permission for `removable-media` that needs to be granted explicitly. Either use the "Snap Store" snap to do it with a graphical utility, or run `snap connect makemkv:removable-media` in a terminal.
